package rw.ingoboka.identity.domain.model;

public enum UserRole {
    CITIZEN,
    AGENT,
    CUSTOMER_SUPPORT,
    INSURER_PRODUCT_MANAGER,
    INSURER_UNDERWRITER,
    INSURER_CLAIMS_OFFICER,
    INSURER_CLAIMS_SUPERVISOR,
    INSURER_FINANCE,
    INSURER_ADMIN,
    PLATFORM_ADMIN,
    AUDITOR,
    INTEGRATION_CLIENT
}
