-- V1: PostgreSQL extensions and base enum types for Ingoboka platform

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TYPE user_role AS ENUM (
    'CITIZEN',
    'AGENT',
    'CUSTOMER_SUPPORT',
    'INSURER_PRODUCT_MANAGER',
    'INSURER_UNDERWRITER',
    'INSURER_CLAIMS_OFFICER',
    'INSURER_CLAIMS_SUPERVISOR',
    'INSURER_FINANCE',
    'INSURER_ADMIN',
    'PLATFORM_ADMIN',
    'AUDITOR',
    'INTEGRATION_CLIENT'
);

CREATE TYPE language_code AS ENUM ('RW', 'EN');

CREATE TYPE gender AS ENUM ('MALE', 'FEMALE', 'OTHER', 'PREFER_NOT_TO_SAY');

CREATE TYPE kyc_status AS ENUM ('PENDING', 'VERIFIED', 'REJECTED', 'MANUAL_REVIEW');
